[project]
name = "project1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pip>=25.2",
    "scikit-learn>=1.7.2",
    "spacy>=3.8.7",
    "wordcloud>=1.9.4",
]
